### ISSUE TITLE
Upgrade org.glassfish.tyrus from 1.17 to 2.0.0 fails

### ISSUE THREAD

**Issue by bergtwvd** [eclipse-ee4j/tyrus#749]
I tried to upgrade the Maven packages from 1.17 to 2.0.0. When I run the application I get the following error:

````
sep. 05, 2021 1:43:20 A.M. org.glassfish.grizzly.http.server.NetworkListener start
INFO: Started listener bound to [0.0.0.0:15556]
sep. 05, 2021 1:43:20 A.M. org.glassfish.grizzly.http.server.HttpServer start
INFO: [HttpServer] Started.
sep. 05, 2021 1:43:20 A.M. org.glassfish.grizzly.http.server.NetworkListener shutdownNow
INFO: Stopped listener bound to [0.0.0.0:15556]
Exception in thread "main" jakarta.websocket.DeploymentException: Class test.tyrus.TestServer is not ServerApplicationConfig descendant nor has @ServerEndpoint annotation.

	at org.glassfish.tyrus.core.ErrorCollector.composeComprehensiveException(ErrorCollector.java:60)
	at org.glassfish.tyrus.server.TyrusServerContainer.start(TyrusServerContainer.java:140)
	at org.glassfish.tyrus.container.grizzly.server.GrizzlyServerContainer$1.start(GrizzlyServerContainer.java:200)
	at org.glassfish.tyrus.server.Server.start(Server.java:205)
	at test.tyrus.TestServer.main(TestServer.java:48)
````

POM:

````
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <groupId>test</groupId>
    <artifactId>tyrus</artifactId>
    <version>1.0</version>
    <packaging>jar</packaging>
    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <maven.compiler.source>11</maven.compiler.source>
        <maven.compiler.target>11</maven.compiler.target>
    </properties>
    
    <dependencies>
        <dependency>
            <groupId>org.glassfish.tyrus</groupId>
            <artifactId>tyrus-server</artifactId>
            <version>2.0.0</version>
        </dependency>
        <dependency>
            <groupId>org.glassfish.tyrus</groupId>
            <artifactId>tyrus-container-grizzly-server</artifactId>
            <version>2.0.0</version>
        </dependency>
        <dependency>
            <groupId>javax.websocket</groupId>
            <artifactId>javax.websocket-api</artifactId>
            <version>1.1</version>
        </dependency>
        <dependency>
            <groupId>jakarta.json</groupId>
            <artifactId>jakarta.json-api</artifactId>
            <version>2.0.0</version>
            <type>jar</type>
        </dependency>
        <dependency>
            <groupId>org.glassfish</groupId>
            <artifactId>jakarta.json</artifactId>
            <version>2.0.1</version>
        </dependency>
    </dependencies>
</project>
````

Source code:

````
package test.tyrus;

import jakarta.json.Json;
import jakarta.json.JsonReader;
import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.io.Reader;
import java.io.Writer;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.websocket.OnClose;
import javax.websocket.OnMessage;
import javax.websocket.OnOpen;
import javax.websocket.Session;
import javax.websocket.server.PathParam;
import javax.websocket.server.ServerEndpoint;
import org.glassfish.tyrus.server.Server;

@ServerEndpoint(value = "/{id}")
public class TestServer {

	@OnOpen
	public void onOpen(@PathParam("id") String id, Session session) {
		System.out.println("OnOpen:" + id + " sessionid=" + session.getId());
	}

	@OnMessage
	public void onMessage(@PathParam("id") String id, Reader reader, Session session) {
		try {
			try (JsonReader jsonReader = Json.createReader(reader); Writer writer = session.getBasicRemote().getSendWriter()) {
				String value = jsonReader.readObject().toString();
				System.out.println(id + ":" + value);
				writer.write(value);
			}
		} catch (IOException ex) {
			Logger.getLogger(TestServer.class.getName()).log(Level.SEVERE, null, ex);
		}
	}

	@OnClose
	public void onClose(@PathParam("id") String id, Session session) {
		System.out.println("OnClose:" + id);
	}

	public static void main(String[] args) throws Exception {
		Server server = new Server("127.0.0.1", 15556, "/", null, TestServer.class);
		server.start();
		BufferedReader reader = new BufferedReader(new InputStreamReader(System.in));
		System.out.println("Please press a key to stop the server.");
		reader.readLine();
		server.stop();
	}
}
````

**Comment by jansupol** [comment]
You cannot use `import javax.websocket`. You need to use `jakarta.websocket`, ie you need to use jakarta.websocket:jakarta.websocket-api:2.0.0.
