### ISSUE TITLE
Version of Tyrus for Jakarta EE 10/GlassFish 7 needed

### ISSUE THREAD

**Issue by arjantijms** [eclipse-ee4j/tyrus#762]
The current version of Tyrus crashes on GF 7 with the following exception:

```
[#|2021-12-16T15:38:51.046+0100|SEVERE|glassfish 7.0|jakarta.enterprise.web.core|_ThreadID=80;_ThreadName=admin-listener(4);_TimeMillis=1639665531046;_LevelValue=1000;|
  java.util.ServiceConfigurationError: jakarta.servlet.ServletContainerInitializer: Provider org.glassfish.tyrus.servlet.TyrusServletContainerInitializer not found
	at java.base/java.util.ServiceLoader.fail(ServiceLoader.java:593)
	at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.nextProviderClass(ServiceLoader.java:1219)
	at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.hasNextService(ServiceLoader.java:1228)
	at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.hasNext(ServiceLoader.java:1273)
	at java.base/java.util.ServiceLoader$2.hasNext(ServiceLoader.java:1309)
	at java.base/java.util.ServiceLoader$3.hasNext(ServiceLoader.java:1393)
	at org.apache.catalina.core.StandardContext.callServletContainerInitializers(StandardContext.java:5656)
	at com.sun.enterprise.web.WebModule.callServletContainerInitializers(WebModule.java:594)
	at org.apache.catalina.core.StandardContext.start(StandardContext.java:5588)
```

Note that "not found" here means that Felix wasn't able to locate all dependencies of the module in which Tyrus lives. Unfortunately the real underlying error is swallowed there.

**Comment by jansupol** [comment]
Is a new Servlet API already in? That could be an issue.

**Comment by jansupol** [comment]
The current state of Tyrus could be released with accepting Servlet 6, but we need to go through a review first.

**Comment by arjantijms** [comment]
> Is a new Servlet API already in? That could be an issue.

GlassFish 7 (the PR at least) has indeed integrated the new Servlet API, which is at version 6.

**Comment by arjantijms** [comment]
> The current state of Tyrus could be released with accepting Servlet 6, but we need to go through a review first.

For now just a milestone would be perfect, those would not need a review AFAIK.

**Comment by jansupol** [comment]
We make 2.0.2 since Tyrus still works with WebSocket 2.0.0 API. Jakarta EE 10 will contain 2.1.0 API and we'll create Tyrus 2.1.0.

**Comment by jansupol** [comment]
2.0.2 is in staging.
