### ISSUE TITLE
NullPointerException in GrizzlyClientFilter

### ISSUE THREAD

**Issue by pjablonski44** [eclipse-ee4j/tyrus#799]
Hi Team,

We're using Tyrus 1.18 in our project and I've seen in the logs of the application one occurence of following log:

2022-06-29 22:13:11 UTC WARNING GRIZZLY0013: Exception during FilterChain execution
java.lang.NullPointerException
	at org.glassfish.tyrus.container.grizzly.client.GrizzlyClientFilter.handleRead(GrizzlyClientFilter.java:248)
	at org.glassfish.grizzly.filterchain.ExecutorResolver$9.execute(ExecutorResolver.java:95)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeFilter(DefaultFilterChain.java:260)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeChainPart(DefaultFilterChain.java:177)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.execute(DefaultFilterChain.java:109)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.process(DefaultFilterChain.java:88)
	at org.glassfish.grizzly.ProcessorExecutor.execute(ProcessorExecutor.java:53)
	at org.glassfish.grizzly.nio.transport.TCPNIOTransport.fireIOEvent(TCPNIOTransport.java:515)
	at org.glassfish.grizzly.strategies.AbstractIOStrategy.fireIOEvent(AbstractIOStrategy.java:89)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.run0(WorkerThreadIOStrategy.java:94)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.access$100(WorkerThreadIOStrategy.java:33)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy$WorkerThreadRunnable.run(WorkerThreadIOStrategy.java:114)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:569)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:549)
	at java.base/java.lang.Thread.run(Thread.java:829)

Looks like the taskProcessor is resolved to null reference here:

![image](https://user-images.githubusercontent.com/18898900/178702035-817db80b-bfc8-4771-b9ec-d28f5c4143e1.png)

It happened once. In the meantime we upgraded to version 1.19 but I can't find any important changes around the failing code between those two versions.
Is it internal issue of the library or could be triggered by wrong configuration?

**Comment by jansupol** [comment]
I suspect this can happen when WebSocket protocol-related HTTP headers are modified by a user. Do you have any idea what could have caused this? Perhaps `ServerEndpointConfig.Configurator#modifyHandshake` method could be a candidate for a user code that could lead to this exception.

I am not saying any other cause could have not created this, but it is too difficult to know from the stacktrace only.
