### ISSUE TITLE
1.20 JDK based client exception

### ISSUE THREAD

**Issue by Hugolarson** [eclipse-ee4j/tyrus#831]
Hello,
For a long time we have used grizzly based client.
When we switched to JDK this exceptions appear sporadically.

23-02-02 11:47:56|org.glassfish.tyrus.container.jdk.client.ClientFilter [ tyrus-jdk-client-126|]:org.glassfish.tyrus.container.jdk.client.ClientFilter processError Connection error has occurred 
<br>java.io.IOException: The semaphore timeout period has expired.
<br>
<br>	at sun.nio.ch.Iocp.<unknown>(Unknown Source)
<br>	at sun.nio.ch.Iocp.access$700(Unknown Source)
<br>	at sun.nio.ch.Iocp$EventHandlerTask.run(Unknown Source)
<br>	at java.lang.Thread.run(Unknown Source)
<br>

**Comment by jansupol** [comment]
Hi, sorry, this is some stack trace from the JDK. We have too little information to know why this is happening. A couple of googling suggests this might also happen when the NIC is broken (which I am not saying is your case). Anyway, we would need more information.

**Comment by Hugolarson** [comment]
Hi,
We have hundreds of clients and once the exception occurs at a site they are relentlessly sprayed tens of times every second.
Would you advice me to revert back to grizzly based client?
Thanks.

**Comment by jansupol** [comment]
Hi, 
I can understand your frustration, but I am sorry I really have no idea how to help with the little information provided.
I do not advise you to revert back; instead, I advise you to try to create a reproducer.

**Comment by Hugolarson** [comment]
Sorry to tell you that I switched back to Grizzly.
