### ISSUE TITLE
GraalVm windows native image. grizzly client 1.20

### ISSUE THREAD

**Issue by Hugolarson** [eclipse-ee4j/tyrus#841]
Hello,

When doing a native image on windows 10. graalvm-ce-java17-22.3.1

[tors mars 09 11:06:40 CET 2023][INFO] [SUB] com.oracle.svm.core.jdk.UnsupportedFeatureError: Runtime reflection is not supported for public void advit.web.server.TyrusWsClient.onError(javax.websocket.Session,java.lang.Throwable)
[tors mars 09 11:06:40 CET 2023][INFO] [SUB]    at org.graalvm.nativeimage.builder/com.oracle.svm.core.util.VMError.unsupportedFeature(VMError.java:89)
[tors mars 09 11:06:40 CET 2023][INFO] [SUB]    at java.base@17.0.6/java.lang.reflect.Method.acquireMethodAccessor(Method.java:76)
[tors mars 09 11:06:40 CET 2023][INFO] [SUB]    at java.base@17.0.6/java.lang.reflect.Method.invoke(Method.java:566)
[tors mars 09 11:06:40 CET 2023][INFO] [SUB]    at org.glassfish.tyrus.core.AnnotatedEndpoint.callMethod(AnnotatedEndpoint.java:551)
[tors mars 09 11:06:40 CET 2023][INFO] [SUB]    at org.glassfish.tyrus.core.AnnotatedEndpoint.onError(AnnotatedEndpoint.java:581)
[tors mars 09 11:06:40 CET 2023][INFO] [SUB]    at org.glassfish.tyrus.core.TyrusEndpointWrapper.onPong(TyrusEndpointWrapper.java:1158)
[tors mars 09 11:06:40 CET 2023][INFO] [SUB]    at org.glassfish.tyrus.core.TyrusWebSocket.onPong(TyrusWebSocket.java:223)
[tors mars 09 11:06:40 CET 2023][INFO] [SUB]    at org.glassfish.tyrus.core.frame.PongFrame.respond(PongFrame.java:46)
[tors mars 09 11:06:40 CET 2023][INFO] [SUB]    at org.glassfish.tyrus.core.ProtocolHandler.process(ProtocolHandler.java:819)
[tors mars 09 11:06:40 CET 2023][INFO] [SUB]    at org.glassfish.tyrus.client.TyrusClientEngine$TyrusReadHandler.handle(TyrusClientEngine.java:725)
[tors mars 09 11:06:40 CET 2023][INFO] [SUB]    at org.glassfish.tyrus.container.grizzly.client.GrizzlyClientFilter$ProcessTask.execute(GrizzlyClientFilter.java:466)
[tors mars 09 11:06:40 CET 2023][INFO] [SUB]    at org.glassfish.tyrus.container.grizzly.client.TaskProcessor.processTask(TaskProcessor.java:91)
[tors mars 09 11:06:40 CET 2023][INFO] [SUB]    at org.glassfish.tyrus.container.grizzly.client.TaskProcessor.processTask(TaskProcessor.java:68)
[tors mars 09 11:06:40 CET 2023][INFO] [SUB]    at org.glassfish.tyrus.container.grizzly.client.GrizzlyClientFilter.handleRead(GrizzlyClientFilter.java:249)
[tors mars 09 11:06:40 CET 2023][INFO] [SUB]    at org.glassfish.grizzly.filterchain.ExecutorResolver$9.execute(ExecutorResolver.java:95)
[tors mars 09 11:06:40 CET 2023][INFO] [SUB]    at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeFilter(DefaultFilterChain.java:260)
[tors mars 09 11:06:40 CET 2023][INFO] [SUB]    at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeChainPart(DefaultFilterChain.java:177)
[tors mars 09 11:06:40 CET 2023][INFO] [SUB]    at org.glassfish.grizzly.filterchain.DefaultFilterChain.execute(DefaultFilterChain.java:109)
[tors mars 09 11:06:40 CET 2023][INFO] [SUB]    at org.glassfish.grizzly.filterchain.DefaultFilterChain.process(DefaultFilterChain.java:88)
[tors mars 09 11:06:40 CET 2023][INFO] [SUB]    at org.glassfish.grizzly.ProcessorExecutor.execute(ProcessorExecutor.java:53)
[tors mars 09 11:06:40 CET 2023][INFO] [SUB]    at org.glassfish.grizzly.nio.transport.TCPNIOTransport.fireIOEvent(TCPNIOTransport.java:515)
[tors mars 09 11:06:40 CET 2023][INFO] [SUB]    at org.glassfish.grizzly.strategies.AbstractIOStrategy.fireIOEvent(AbstractIOStrategy.java:89)
[tors mars 09 11:06:40 CET 2023][INFO] [SUB]    at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.run0(WorkerThreadIOStrategy.java:94)
[tors mars 09 11:06:40 CET 2023][INFO] [SUB]    at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.access$100(WorkerThreadIOStrategy.java:33)
[tors mars 09 11:06:40 CET 2023][INFO] [SUB]    at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy$WorkerThreadRunnable.run(WorkerThreadIOStrategy.java:114)
[tors mars 09 11:06:40 CET 2023][INFO] [SUB]    at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:569)
[tors mars 09 11:06:40 CET 2023][INFO] [SUB]    at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:549)
[tors mars 09 11:06:40 CET 2023][INFO] [SUB]    at java.base@17.0.6/java.lang.Thread.run(Thread.java:833)
[tors mars 09 11:06:40 CET 2023][INFO] [SUB]    at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:775)
[tors mars 09 11:06:40 CET 2023][INFO] [SUB]    at org.graalvm.nativeimage.builder/com.oracle.svm.core.windows.WindowsPlatformThreads.osThreadStartRoutine(WindowsPlatformThreads.java:178)

**Comment by jansupol** [comment]
Tyrus has not been tested with GraalVM, yet. Perhaps if there is more requirement, we can give it some attention.
