### ISSUE TITLE
Tryus client 2.1.5 doesn't export new package org/glassfish/tyrus/client/exception

### ISSUE THREAD

**Issue by arjantijms** [eclipse-ee4j/tyrus#888]
For Tyrus 2.1.5 the client jar added a new package `org.glassfish.tyrus.client.exception`. This package is used by at least `tyrus-container-grizzly-client-2.1.5.jar`. The package is however not exported in its MANIFEST.MF.

In an OSGi environment such as GlassFish, this leads to an exception such as:

```
Exception: java.util.ServiceConfigurationError: jakarta.websocket.ContainerProvider: Provider org.glassfish.tyrus.container.grizzly.client.GrizzlyContainerProvider not found
	at java.base/java.util.ServiceLoader.fail(ServiceLoader.java:589)
	at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.nextProviderClass(ServiceLoader.java:1212)
	at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.hasNextService(ServiceLoader.java:1221)
	at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator$1.run(ServiceLoader.java:1268)
	at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator$1.run(ServiceLoader.java:1267)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.hasNext(ServiceLoader.java:1270)
	at java.base/java.util.ServiceLoader$2.hasNext(ServiceLoader.java:1300)
	at java.base/java.util.ServiceLoader$3.hasNext(ServiceLoader.java:1385)
	at jakarta.websocket.ContainerProvider.getWebSocketContainerImpl(ContainerProvider.java:64)
	at jakarta.websocket.ContainerProvider.access$000(ContainerProvider.java:36)
	at jakarta.websocket.ContainerProvider$1.run(ContainerProvider.java:56)
	at jakarta.websocket.ContainerProvider$1.run(ContainerProvider.java:53)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at jakarta.websocket.ContainerProvider.getWebSocketContainer(ContainerProvider.java:53)
```

The simple fix is to add the export, e.g. in META-INF/MANIFEST:

```
Export-Package: org.glassfish.tyrus.client;version="2.1.5";uses:="jaka
 rta.websocket,javax.net.ssl,org.glassfish.tyrus.core,org.glassfish.ty
 rus.spi",org.glassfish.tyrus.client.exception;version="2.1.5"
```

**Comment by jansupol** [comment]
@arjantijms Thanks!
